ALTER TABLE users
    MODIFY nome VARCHAR(255) NOT NULL,
    MODIFY email VARCHAR(255) NOT NULL,
    MODIFY senha VARCHAR(255) NOT NULL,
    MODIFY cargo VARCHAR(255) NOT NULL,
    MODIFY telefone VARCHAR(255) NOT NULL,
    MODIFY tipo_usuario VARCHAR(255) NOT NULL;